### ISSUE TITLE
ModuleNotFoundError: No module named 'openbabel'

### ISSUE THREAD

**Issue by purnawanpp** [alanwilter/acpype#76]
Hi Alan, I have upgraded my conda, and I get this error to running acpype, 
==========================================================================
| ACPYPE: AnteChamber PYthon Parser interfacE v. 2022.1.3 (c) 2022 AWSdS |
==========================================================================
WARNING: no charge value given, trying to guess one...
==> ... charge set to 0
==> ... converting pdb input file to mol2 input file
==> * Babel OK *
==> Executing Antechamber...
==> AC output file present... doing nothing
==> * Antechamber OK *
==> * Parmchk OK *
==> Topologies files already present... doing nothing
==> * Tleap OK *
==> Removing temporary files...
ERROR: ACPYPE FAILED: No module named 'openbabel'
Traceback (most recent call last):
  File "/home/renoir/anaconda3/lib/python3.9/site-packages/acpype/cli.py", line 141, in init_main
    molecule.createMolTopol()
  File "/home/renoir/anaconda3/lib/python3.9/site-packages/acpype/topol.py", line 1108, in createMolTopol
    self.molTopol = MolTopol(
  File "/home/renoir/anaconda3/lib/python3.9/site-packages/acpype/topol.py", line 3419, in __init__
    self.getChirals()
  File "/home/renoir/anaconda3/lib/python3.9/site-packages/acpype/topol.py", line 1446, in getChirals
    if checkOpenBabelVersion() >= 300:
  File "/home/renoir/anaconda3/lib/python3.9/site-packages/acpype/utils.py", line 18, in checkOpenBabelVersion
    import openbabel as obl
ModuleNotFoundError: No module named 'openbabel'
Total time of execution: less than a second
Do you know solved this problem?
I can run obabel with terminal but getting eror when i run _acpype -i Ligand.pdb_

**Comment by alanwilter** [comment]
Try this:

```bash
conda create -n acpype_test acpype -y
conda activate acpype_test
acpype -i CCCC
```
If that **DOES NOT** work (but that worked whatever I tried, Mac and Linux), then the problem is your `conda`.

**Comment by purnawanpp** [comment]
Thanks, Alan, it works when I used _conda activate_ in the terminal
